// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqtzvciaxbsdmwrijmgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xdHp2Y2lheGJzZG13cmlqbWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzMTU0OTgsImV4cCI6MjA3Nzg5MTQ5OH0.K8e47DuW1ypm9zCu1omJwVTNo6vkYpnK5cN4w4ixCJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});